# Generated by Django 4.0.5 on 2022-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_difficulty_delete_difficultytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
